import os
from dotenv import load_dotenv

load_dotenv()


class Config(object):
	DEBUG = False
	TESTING = False
	AI_API_SECRET_KEY = os.getenv('AI_API_SECRET_KEY')
	ALLOWED_EXTENSIONS = os.getenv('ALLOWED_EXTENSIONS')
	MAX_CONTENT_LENGTH = os.getenv('MAX_CONTENT_LENGTH')


class DevelopmentConfig(Config):  # intermediate state
	DEBUG = True
	TESTING = False
	AI_API_SECRET_KEY = os.getenv('AI_API_SECRET_KEY')
	ALLOWED_EXTENSIONS = os.getenv('ALLOWED_EXTENSIONS')
	MAX_CONTENT_LENGTH = os.getenv('MAX_CONTENT_LENGTH')
	APPLICATION_URL = os.getenv('APPLICATION_URL')
	UPLOAD_FOLDER = os.getenv('UPLOAD_FOLDER')
	SENDER_EMAIL = os.getenv('SENDER_EMAIL')
	EMAIL_APP_PASSWORD = os.getenv('EMAIL_APP_PASSWORD')
	SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')


class ProductionConfig(Config):  # final state
	DEBUG = False
	TESTING = False
	AI_API_SECRET_KEY = os.getenv('AI_API_SECRET_KEY')
	ALLOWED_EXTENSIONS = os.getenv('ALLOWED_EXTENSIONS')
	MAX_CONTENT_LENGTH = os.getenv('MAX_CONTENT_LENGTH')
	APPLICATION_URL = os.getenv('APPLICATION_URL')
	UPLOAD_FOLDER = os.getenv('UPLOAD_FOLDER')
	SENDER_EMAIL = os.getenv('SENDER_EMAIL')
	EMAIL_APP_PASSWORD = os.getenv('EMAIL_APP_PASSWORD')
	SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
	SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS')
